language: php

php:
  - 5.6
  - 7.0

install:
  - composer install
  - composer require satooshi/php-coveralls --dev

script:
  - phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
